version: '3.4'
services:
 cursesapi:
   image: ${DOCKER_REGISTRY-}cursesapi
   build:
     context: .
     dockerfile: CoursesAPI/Dockerfile
   depends_on:
   - sqldata
 studentsapi:
   image: ${DOCKER_REGISTRY-}studentsapi
   build:
     context: .
     dockerfile: StudentsAPI/Dockerfile
   depends_on:
   - sqldata
 sqldata:
   image: mcr.microsoft.com/mssql/server:2019-latest